# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(770, 243)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(770, 243))
        MainWindow.setMaximumSize(QtCore.QSize(770, 243))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.address_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.address_bar.setGeometry(QtCore.QRect(140, 20, 621, 31))
        self.address_bar.setObjectName("address_bar")
        self.address_label = QtWidgets.QLabel(self.centralwidget)
        self.address_label.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.address_label.setObjectName("address_label")
        self.calendar_group = QtWidgets.QGroupBox(self.centralwidget)
        self.calendar_group.setGeometry(QtCore.QRect(10, 140, 111, 101))
        self.calendar_group.setObjectName("calendar_group")
        self.khorshidi_choice = QtWidgets.QRadioButton(self.calendar_group)
        self.khorshidi_choice.setGeometry(QtCore.QRect(0, 30, 128, 25))
        self.khorshidi_choice.setObjectName("khorshidi_choice")
        self.georgian_choice = QtWidgets.QRadioButton(self.calendar_group)
        self.georgian_choice.setGeometry(QtCore.QRect(0, 60, 131, 31))
        self.georgian_choice.setObjectName("georgian_choice")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(320, 150, 441, 81))
        self.start_button.setObjectName("start_button")
        self.start_button.
        self.file_counter = QtWidgets.QLCDNumber(self.centralwidget)
        self.file_counter.setGeometry(QtCore.QRect(140, 150, 161, 41))
        self.file_counter.setObjectName("file_counter")
        self.file_counter_label = QtWidgets.QLabel(self.centralwidget)
        self.file_counter_label.setGeometry(QtCore.QRect(150, 200, 141, 21))
        self.file_counter_label.setObjectName("file_counter_label")
        self.address_bar_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.address_bar_2.setGeometry(QtCore.QRect(140, 60, 621, 31))
        self.address_bar_2.setText("")
        self.address_bar_2.setObjectName("address_bar_2")
        self.address_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.address_label_2.setGeometry(QtCore.QRect(20, 66, 91, 20))
        self.address_label_2.setObjectName("address_label_2")
        self.address_bar_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.address_bar_3.setGeometry(QtCore.QRect(140, 100, 621, 31))
        self.address_bar_3.setText("")
        self.address_bar_3.setObjectName("address_bar_3")
        self.address_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.address_label_3.setGeometry(QtCore.QRect(20, 100, 91, 20))
        self.address_label_3.setObjectName("address_label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Categorizer"))
        self.address_bar.setToolTip(_translate("MainWindow", "Address of file to be organized"))
        self.address_label.setText(_translate("MainWindow", "Folder address"))
        self.calendar_group.setToolTip(_translate("MainWindow", "Select the calendar to be used in logging system"))
        self.calendar_group.setTitle(_translate("MainWindow", "Calendar"))
        self.khorshidi_choice.setText(_translate("MainWindow", "Khoshidi"))
        self.georgian_choice.setText(_translate("MainWindow", "Georgian"))
        self.start_button.setToolTip(_translate("MainWindow", "Press to start to categorize files"))
        self.start_button.setText(_translate("MainWindow", "Categorize"))
        self.file_counter.setToolTip(_translate("MainWindow", "Total number of files processed till now"))
        self.file_counter_label.setText(_translate("MainWindow", "Files Processed"))
        self.address_bar_2.setToolTip(_translate("MainWindow", "Where the file Categories and file be there in the end. make sure it has enough space"))
        self.address_label_2.setText(_translate("MainWindow", "Destination"))
        self.address_bar_3.setToolTip(_translate("MainWindow", "Enter the log file address here"))
        self.address_label_3.setText(_translate("MainWindow", "Log File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
